apiVersion: apps/v1
kind: Deployment
metadata:
  name: disasterservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: disasterservice
  template:
    metadata:
      labels:
        app: disasterservice
    spec:
      containers:
      - name: disasterservice
        image: salaheddinerossi/disasterservice:latest
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://db-postgresql-ams3-30348-do-user-14445709-0.c.db.ondigitalocean.com:25060/defaultdb?useSSL=true&requireSSL=true"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: authservice-secrets
              key: datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authservice-secrets
              key: datasource-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: authservice-secrets
              key: jwt-secret

